/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ui/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case */
        get: operations["get_case_ui_cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/cases/{case_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evidence */
        get: operations["get_evidence_ui_cases__case_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/cases/{case_id}/hypotheses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Hypotheses */
        get: operations["get_hypotheses_ui_cases__case_id__hypotheses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/cases/{case_id}/reasoning-context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Context */
        get: operations["get_context_ui_cases__case_id__reasoning_context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CaseBudget */
        CaseBudget: {
            /** Max Tool Calls */
            max_tool_calls: number;
            /**
             * Used Tool Calls
             * @default 0
             */
            used_tool_calls: number;
        };
        /**
         * CaseStatus
         * @enum {string}
         */
        CaseStatus: "NEW" | "INVESTIGATING" | "WAITING" | "ESCALATED" | "CLOSED";
        /**
         * ClaimType
         * @enum {string}
         */
        ClaimType: "REQUEST_SENT" | "HTTP_RESPONSE_STATUS" | "FUND_BUSINESS_STATUS" | "LOAN_NO_PRESENT" | "LOAN_NOTE_REFERENCE" | "PAYMENT_FINALITY" | "PAYMENT_TRANSACTION_ID" | "PAYMENT_AMOUNT" | "PAYMENT_CURRENCY" | "PAYMENT_CUSTOMER_REF" | "PAYMENT_BENEFICIARY_REF" | "PAYMENT_ACCOUNT_REF" | "TRANSACTION_FUND_REQUEST_ID" | "CALLBACK_GATEWAY_RECEIVED" | "CALLBACK_SIGNATURE_VERIFIED" | "CALLBACK_PROTOCOL_VERSION" | "MESSAGE_CONSUME_STATUS" | "MESSAGE_DLQ" | "MESSAGE_ERROR_CODE" | "MESSAGE_ERROR_FIELD" | "MESSAGE_EXPECTED_FIELD_TYPE" | "MESSAGE_ACTUAL_FIELD_TYPE" | "ACCOUNTING_ENTRY_PRESENT" | "ASSET_STATUS" | "GUARANTEE_STATUS" | "GUARANTEE_VERSION" | "ASSET_DELIVERY_STATUS" | "PROTOCOL_FIELD_TYPE" | "PROTOCOL_BUSINESS_SEMANTICS" | "SOURCE_LOOKUP_STATUS";
        /**
         * Completeness
         * @enum {string}
         */
        Completeness: "COMPLETE" | "PARTIAL" | "UNKNOWN";
        /** ContextBudget */
        ContextBudget: {
            /**
             * Max Serialized Chars
             * @default 60000
             */
            max_serialized_chars: number;
            /**
             * Max Fact Capsules
             * @default 64
             */
            max_fact_capsules: number;
            /**
             * Max Hypothesis Capsules
             * @default 16
             */
            max_hypothesis_capsules: number;
            /**
             * Max Gap Capsules
             * @default 24
             */
            max_gap_capsules: number;
            /**
             * Max History Items
             * @default 20
             */
            max_history_items: number;
            /**
             * Max Relation Ref Preview
             * @default 4
             */
            max_relation_ref_preview: number;
            /**
             * Max Identity Transaction Preview
             * @default 3
             */
            max_identity_transaction_preview: number;
        };
        /** ContextBudgetUsage */
        ContextBudgetUsage: {
            /** Serialized Chars */
            serialized_chars: number;
            /** Approximate Tokens */
            approximate_tokens: number;
            /** Fact Capsules */
            fact_capsules: number;
            /** Hypothesis Capsules */
            hypothesis_capsules: number;
            /** Gap Capsules */
            gap_capsules: number;
            /** History Items */
            history_items: number;
            limits: components["schemas"]["ContextBudget"];
            /**
             * Estimator
             * @default unicode_chars_div_3_ceiling_v1
             */
            estimator: string;
        };
        /** ContextSectionTrust */
        ContextSectionTrust: {
            /**
             * Task
             * @default TRUSTED_CONTROL
             * @constant
             */
            task: "TRUSTED_CONTROL";
            /**
             * Financial Subject
             * @default TRUSTED_CONTROL
             * @constant
             */
            financial_subject: "TRUSTED_CONTROL";
            /**
             * Safety Constraints
             * @default TRUSTED_CONTROL
             * @constant
             */
            safety_constraints: "TRUSTED_CONTROL";
            /**
             * Available Tools
             * @default TRUSTED_CONTROL
             * @constant
             */
            available_tools: "TRUSTED_CONTROL";
            /**
             * Budget
             * @default TRUSTED_CONTROL
             * @constant
             */
            budget: "TRUSTED_CONTROL";
            /**
             * Current Facts
             * @default UNTRUSTED_EXTERNAL_DATA
             * @constant
             */
            current_facts: "UNTRUSTED_EXTERNAL_DATA";
            /**
             * History Digest
             * @default UNTRUSTED_EXTERNAL_DATA
             * @constant
             */
            history_digest: "UNTRUSTED_EXTERNAL_DATA";
            /**
             * Financial Identity
             * @default DETERMINISTIC_DERIVED
             * @constant
             */
            financial_identity: "DETERMINISTIC_DERIVED";
            /**
             * Active Hypotheses
             * @default DETERMINISTIC_DERIVED
             * @constant
             */
            active_hypotheses: "DETERMINISTIC_DERIVED";
            /**
             * Resolved Hypotheses Summary
             * @default DETERMINISTIC_DERIVED
             * @constant
             */
            resolved_hypotheses_summary: "DETERMINISTIC_DERIVED";
            /**
             * Open Evidence Gaps
             * @default DETERMINISTIC_DERIVED
             * @constant
             */
            open_evidence_gaps: "DETERMINISTIC_DERIVED";
        };
        /**
         * Currency
         * @enum {string}
         */
        Currency: "CNY" | "USD";
        /**
         * EstimateClass
         * @enum {string}
         */
        EstimateClass: "LOW" | "MEDIUM";
        /**
         * EvidenceStrength
         * @enum {string}
         */
        EvidenceStrength: "AUTHORITATIVE" | "STRONG" | "SUPPORTING" | "WEAK" | "HINT";
        /** FactCapsule */
        FactCapsule: {
            claim_type: components["schemas"]["ClaimType"];
            /** Value */
            value: boolean | number | string;
            subject: components["schemas"]["FactSubject"];
            /**
             * Business Time
             * Format: date-time
             */
            business_time: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            freshness: components["schemas"]["Freshness"];
            completeness: components["schemas"]["Completeness"];
            source: components["schemas"]["FactSource"];
            /** Protocol Version */
            protocol_version: string | null;
            /** Evidence Refs */
            evidence_refs: string[];
        };
        /** FactSource */
        FactSource: {
            tool: components["schemas"]["ToolName"];
            source_kind: components["schemas"]["SourceKind"];
            /** Source Version */
            source_version: string | null;
            /** Source As Of */
            source_as_of: string | null;
        };
        /** FactSubject */
        FactSubject: {
            kind: components["schemas"]["SubjectKind"];
            /** Identifier */
            identifier: string;
            /** Field */
            field: string | null;
            /** Internal Order Id */
            internal_order_id: string;
        };
        /** FinancialSubject */
        FinancialSubject: {
            /** Expected Principal Minor */
            expected_principal_minor: number;
            currency: components["schemas"]["Currency"];
            /** Customer Ref */
            customer_ref: string;
            /** Expected Beneficiary Ref */
            expected_beneficiary_ref: string;
            /** Expected Account Ref */
            expected_account_ref: string;
        };
        /**
         * Freshness
         * @enum {string}
         */
        Freshness: "CURRENT" | "STALE" | "UNKNOWN";
        /** GapCapsule */
        GapCapsule: {
            /** Gap Id */
            gap_id: string;
            /** Question */
            question: string;
            /** Required Claim Types */
            required_claim_types: (components["schemas"]["ClaimType"] | components["schemas"]["UncollectedClaimType"])[];
            priority: components["schemas"]["PriorityClass"];
            status: components["schemas"]["GapStatus"];
            /** Related Hypotheses */
            related_hypotheses: components["schemas"]["HypothesisId"][];
            /** Evidence Refs */
            evidence_refs: string[];
        };
        /**
         * GapStatus
         * @enum {string}
         */
        GapStatus: "OPEN" | "SATISFIED" | "UNAVAILABLE";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoricalStateGroup */
        HistoricalStateGroup: {
            claim_type: components["schemas"]["ClaimType"];
            subject: components["schemas"]["FactSubject"];
            /** Protocol Version */
            protocol_version: string | null;
            /** First Observed Value */
            first_observed_value: boolean | number | string;
            /** Last Observed Value */
            last_observed_value: boolean | number | string;
            /**
             * First Business Time
             * Format: date-time
             */
            first_business_time: string;
            /**
             * Last Business Time
             * Format: date-time
             */
            last_business_time: string;
            last_freshness: components["schemas"]["Freshness"];
            references: components["schemas"]["ReferenceRange"];
        };
        /** HistoryDigest */
        HistoryDigest: {
            /** Tool Calls Used */
            tool_calls_used: number;
            /** Evidence Count */
            evidence_count: number;
            /** Latest Observation Time */
            latest_observation_time: string | null;
            /** Repeated Lookup Groups */
            repeated_lookup_groups: components["schemas"]["RepeatedLookupGroup"][];
            /** State Transitions */
            state_transitions: components["schemas"]["HistoricalStateGroup"][];
            /**
             * Lookup History Complete
             * @default false
             */
            lookup_history_complete: boolean;
        };
        /** HypothesisCapsule */
        HypothesisCapsule: {
            hypothesis_id: components["schemas"]["HypothesisId"];
            kind: components["schemas"]["HypothesisKind"];
            /** Statement */
            statement: string;
            status: components["schemas"]["HypothesisStatus"];
            /** Decisive Evidence Refs */
            decisive_evidence_refs: string[];
            /**
             * Supporting Ref Preview
             * @default []
             */
            supporting_ref_preview: string[];
            /**
             * Contradicting Ref Preview
             * @default []
             */
            contradicting_ref_preview: string[];
            /** Supporting Ref Count */
            supporting_ref_count: number;
            /** Contradicting Ref Count */
            contradicting_ref_count: number;
            /** Supporting Refs Digest */
            supporting_refs_digest: string;
            /** Contradicting Refs Digest */
            contradicting_refs_digest: string;
            /** Open Gap Ids */
            open_gap_ids: string[];
            /** Reason */
            reason: string;
        };
        /** HypothesisDefinition */
        HypothesisDefinition: {
            hypothesis_id: components["schemas"]["HypothesisId"];
            kind: components["schemas"]["HypothesisKind"];
            /** Statement */
            statement: string;
            /** Description */
            description: string;
            /** Confirmation Rule Id */
            confirmation_rule_id: string;
            /** Elimination Rule Id */
            elimination_rule_id: string;
            /** Relevant Claim Types */
            relevant_claim_types: components["schemas"]["ClaimType"][];
            parent_hypothesis_id?: components["schemas"]["HypothesisId"] | null;
        };
        /**
         * HypothesisId
         * @enum {string}
         */
        HypothesisId: "H1" | "H2" | "H3" | "H4" | "H5" | "H6" | "H6_SCHEMA_MISMATCH" | "H6_STALE_CONSUMER_SCHEMA" | "H7" | "H8";
        /**
         * HypothesisKind
         * @enum {string}
         */
        HypothesisKind: "CAUSAL" | "STATE" | "SEMANTIC_GUARD";
        /**
         * HypothesisStatus
         * @enum {string}
         */
        HypothesisStatus: "UNKNOWN" | "POSSIBLE" | "SUPPORTED" | "CONFIRMED" | "ELIMINATED";
        /**
         * IdentityDimension
         * @enum {string}
         */
        IdentityDimension: "FINALITY" | "TRANSACTION" | "REQUEST" | "AMOUNT" | "CURRENCY" | "CUSTOMER" | "BENEFICIARY" | "ACCOUNT";
        /**
         * IdentityMatch
         * @enum {string}
         */
        IdentityMatch: "MATCH" | "MISMATCH" | "UNKNOWN";
        /** LookupScope */
        LookupScope: {
            /** Internal Order Id */
            internal_order_id: string;
            /** Protocol Version */
            protocol_version: string | null;
            /** Effective At */
            effective_at: string | null;
        };
        /**
         * ObservationStatus
         * @enum {string}
         */
        ObservationStatus: "OK" | "TIMEOUT" | "NOT_FOUND";
        /** OmissionGroup */
        OmissionGroup: {
            reason: components["schemas"]["OmissionReason"];
            /** Count */
            count: number;
            /** Evidence Ids Digest */
            evidence_ids_digest: string;
        };
        /**
         * OmissionReason
         * @enum {string}
         */
        OmissionReason: "ELIGIBILITY_DENIED" | "REPEATED_LOOKUP" | "HISTORICAL_SUPERSEDED" | "IRRELEVANT_TO_ACTIVE_HYPOTHESES" | "SIZE_BUDGET" | "RELATION_COMPACTED" | "IDENTITY_COMPACTED";
        /** OmittedEvidenceSummary */
        OmittedEvidenceSummary: {
            /** Total Evidence */
            total_evidence: number;
            /** Selected */
            selected: number;
            /** Omitted */
            omitted: components["schemas"]["OmissionGroup"][];
        };
        /** PaymentIdentityContext */
        PaymentIdentityContext: {
            result: components["schemas"]["IdentityMatch"];
            /** Mismatch Dimensions */
            mismatch_dimensions: components["schemas"]["IdentityDimension"][];
            /** Unknown Dimensions */
            unknown_dimensions: components["schemas"]["IdentityDimension"][];
            /** Candidate Transaction Count */
            candidate_transaction_count: number;
            /** Transaction Ref Preview */
            transaction_ref_preview: string[];
            /** Transaction Refs Digest */
            transaction_refs_digest: string;
            /** Evidence Ref Count */
            evidence_ref_count: number;
            /** Evidence Refs Digest */
            evidence_refs_digest: string;
            /** Evidence Refs */
            evidence_refs: string[];
            /** Verification Version */
            verification_version: string;
        };
        /**
         * PriorityClass
         * @enum {string}
         */
        PriorityClass: "SAFETY_CRITICAL" | "DISCRIMINATING" | "SUPPORTING";
        /** ReasoningContextSnapshot */
        ReasoningContextSnapshot: {
            /** Snapshot Id */
            snapshot_id: string;
            /**
             * @default {
             *       "task": "TRUSTED_CONTROL",
             *       "financial_subject": "TRUSTED_CONTROL",
             *       "safety_constraints": "TRUSTED_CONTROL",
             *       "available_tools": "TRUSTED_CONTROL",
             *       "budget": "TRUSTED_CONTROL",
             *       "current_facts": "UNTRUSTED_EXTERNAL_DATA",
             *       "history_digest": "UNTRUSTED_EXTERNAL_DATA",
             *       "financial_identity": "DETERMINISTIC_DERIVED",
             *       "active_hypotheses": "DETERMINISTIC_DERIVED",
             *       "resolved_hypotheses_summary": "DETERMINISTIC_DERIVED",
             *       "open_evidence_gaps": "DETERMINISTIC_DERIVED"
             *     }
             */
            section_trust: components["schemas"]["ContextSectionTrust"];
            /** Case Id */
            case_id: string;
            /** Internal Order Id */
            internal_order_id: string;
            /** Context Schema Version */
            context_schema_version: string;
            /** Eligibility Policy Version */
            eligibility_policy_version: string;
            /** Compaction Policy Version */
            compaction_policy_version: string;
            /** Context Policy Version */
            context_policy_version: string;
            /** Hypothesis Rule Version */
            hypothesis_rule_version: string;
            /**
             * Assembled At
             * Format: date-time
             */
            assembled_at: string;
            /** Case Fingerprint */
            case_fingerprint: string;
            /** Evidence Fingerprint */
            evidence_fingerprint: string;
            /** Hypothesis Input Fingerprint */
            hypothesis_input_fingerprint: string;
            /** Hypothesis Graph Fingerprint */
            hypothesis_graph_fingerprint: string;
            /** Policy Fingerprint */
            policy_fingerprint: string;
            task: components["schemas"]["TaskContext"];
            financial_subject: components["schemas"]["FinancialSubject"] | null;
            financial_identity: components["schemas"]["PaymentIdentityContext"];
            /** Current Facts */
            current_facts: components["schemas"]["FactCapsule"][];
            /** Active Hypotheses */
            active_hypotheses: components["schemas"]["HypothesisCapsule"][];
            /** Resolved Hypotheses Summary */
            resolved_hypotheses_summary: components["schemas"]["ResolvedHypothesisSummary"][];
            /** Open Evidence Gaps */
            open_evidence_gaps: components["schemas"]["GapCapsule"][];
            safety_constraints: components["schemas"]["SafetyContext"];
            budget: components["schemas"]["RuntimeBudgetContext"];
            /** Available Tools */
            available_tools: components["schemas"]["ToolCapability"][];
            history_digest: components["schemas"]["HistoryDigest"];
            /** Selected Evidence Refs */
            selected_evidence_refs: string[];
            omitted_evidence_summary: components["schemas"]["OmittedEvidenceSummary"];
            context_budget_usage: components["schemas"]["ContextBudgetUsage"];
        };
        /** ReferenceRange */
        ReferenceRange: {
            /** Count */
            count: number;
            /** First Ref */
            first_ref: string;
            /** Latest Ref */
            latest_ref: string;
            /** Range Digest */
            range_digest: string;
        };
        /** RepeatedLookupGroup */
        RepeatedLookupGroup: {
            tool: components["schemas"]["ToolName"];
            scope: components["schemas"]["LookupScope"];
            status: components["schemas"]["ObservationStatus"];
            /**
             * First Observed At
             * Format: date-time
             */
            first_observed_at: string;
            /**
             * Last Observed At
             * Format: date-time
             */
            last_observed_at: string;
            latest_freshness: components["schemas"]["Freshness"];
            latest_completeness: components["schemas"]["Completeness"];
            references: components["schemas"]["ReferenceRange"];
            /**
             * Latest Consecutive Count
             * @default 0
             */
            latest_consecutive_count: number;
        };
        /** ResolvedHypothesisSummary */
        ResolvedHypothesisSummary: {
            hypothesis_id: components["schemas"]["HypothesisId"];
            /** Statement */
            statement: string;
            status: components["schemas"]["HypothesisStatus"];
            /** Decisive Evidence Refs */
            decisive_evidence_refs: string[];
        };
        /** RuntimeBudgetContext */
        RuntimeBudgetContext: {
            /** Max Tool Calls */
            max_tool_calls: number;
            /** Used Tool Calls */
            used_tool_calls: number;
            /** Remaining Tool Calls */
            remaining_tool_calls: number;
            /** Investigation Allowed */
            investigation_allowed: boolean;
        };
        /** SafetyContext */
        SafetyContext: {
            /** Invariants */
            invariants: components["schemas"]["SafetyInvariant"][];
            /** Forbidden Actions */
            forbidden_actions: string[];
        };
        /**
         * SafetyInvariant
         * @enum {string}
         */
        SafetyInvariant: "NO_NEW_FINANCIAL_INTENT" | "UNKNOWN_IS_NOT_FAILED" | "TOOL_SUCCESS_IS_NOT_BUSINESS_OUTCOME" | "REQUIRE_COMPLETE_PAYMENT_IDENTITY" | "READ_ONLY_INVESTIGATION" | "NO_SELF_DECLARED_CASE_SUCCESS" | "EVIDENCE_REFERENCES_REQUIRED";
        /**
         * SourceKind
         * @enum {string}
         */
        SourceKind: "PRIMARY" | "REPLICA" | "CACHE" | "INDEX";
        /**
         * SubjectKind
         * @enum {string}
         */
        SubjectKind: "ORDER" | "FUND_REQUEST" | "TRANSACTION" | "CALLBACK" | "MESSAGE" | "PROTOCOL";
        /** TaskContext */
        TaskContext: {
            /** Goal */
            goal: string;
            /** Success Criteria */
            success_criteria: string[];
            /** Stop Conditions */
            stop_conditions: string[];
            /** Escalation Conditions */
            escalation_conditions: string[];
            /** Forbidden Outcomes */
            forbidden_outcomes: string[];
        };
        /** ToolCapability */
        ToolCapability: {
            tool_name: components["schemas"]["ToolName"];
            /** Description */
            description: string;
            /** Produces Claim Types */
            produces_claim_types: components["schemas"]["ClaimType"][];
            /**
             * Contributes Requirements
             * @default []
             */
            contributes_requirements: components["schemas"]["UncollectedClaimType"][];
            /** @default READ_ONLY */
            risk_class: components["schemas"]["ToolRisk"];
            data_classification: components["schemas"]["ToolDataClass"];
            /** @default LOW */
            estimated_cost_class: components["schemas"]["EstimateClass"];
            /** @default LOW */
            estimated_latency_class: components["schemas"]["EstimateClass"];
        };
        /**
         * ToolDataClass
         * @enum {string}
         */
        ToolDataClass: "BUSINESS" | "BUSINESS_RULE" | "TOKENIZED_FINANCIAL_IDENTITY";
        /**
         * ToolName
         * @enum {string}
         */
        ToolName: "get_asset_order" | "get_guarantee_order" | "get_fund_order" | "get_payment_transaction" | "get_loan_note" | "get_callback_gateway" | "get_callback_raw" | "get_messages" | "get_accounting" | "get_request_trace" | "get_asset_delivery" | "get_protocol";
        /**
         * ToolRisk
         * @enum {string}
         */
        ToolRisk: "READ_ONLY";
        /** UICase */
        UICase: {
            /** Case Id */
            case_id: string;
            /** Internal Order Id */
            internal_order_id: string;
            status: components["schemas"]["CaseStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            budget: components["schemas"]["CaseBudget"];
            financial_subject: components["schemas"]["FinancialSubject"] | null;
        };
        /** UIEvidence */
        UIEvidence: {
            claim_type: components["schemas"]["ClaimType"];
            /** Value */
            value: boolean | number | string;
            subject: components["schemas"]["FactSubject"];
            /**
             * Business Time
             * Format: date-time
             */
            business_time: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            freshness: components["schemas"]["Freshness"];
            completeness: components["schemas"]["Completeness"];
            source: components["schemas"]["FactSource"];
            /** Protocol Version */
            protocol_version: string | null;
            /** Evidence Refs */
            evidence_refs: string[];
            /** Evidence Id */
            evidence_id: string;
            /** Observation Id */
            observation_id: string;
            /** Event Time */
            event_time: string | null;
            strength: components["schemas"]["EvidenceStrength"];
            /** Extractor Version */
            extractor_version: string;
        };
        /** UIEvidenceList */
        UIEvidenceList: {
            /** Items */
            items: components["schemas"]["UIEvidence"][];
            /** Total */
            total: number;
            /** Eligibility Denied Count */
            eligibility_denied_count: number;
        };
        /** UIGap */
        UIGap: {
            /** Gap Id */
            gap_id: string;
            /** Case Id */
            case_id: string;
            /** Hypothesis Ids */
            hypothesis_ids: components["schemas"]["HypothesisId"][];
            /** Question */
            question: string;
            /** Required Claim Types */
            required_claim_types: (components["schemas"]["ClaimType"] | components["schemas"]["UncollectedClaimType"])[];
            status: components["schemas"]["GapStatus"];
            /** Reason */
            reason: string;
            priority_class: components["schemas"]["PriorityClass"];
            /** Evidence Refs */
            evidence_refs: string[];
        };
        /** UIHypothesisGraph */
        UIHypothesisGraph: {
            /** Case Id */
            case_id: string;
            /** Rule Version */
            rule_version: string;
            /** Definitions */
            definitions: components["schemas"]["HypothesisDefinition"][];
            /** Hypotheses */
            hypotheses: components["schemas"]["UIHypothesisState"][];
            /** Open Gaps */
            open_gaps: components["schemas"]["UIGap"][];
        };
        /** UIHypothesisState */
        UIHypothesisState: {
            hypothesis_id: components["schemas"]["HypothesisId"];
            status: components["schemas"]["HypothesisStatus"];
            /** Supporting Evidence Refs */
            supporting_evidence_refs: string[];
            /** Contradicting Evidence Refs */
            contradicting_evidence_refs: string[];
            /** Decisive Evidence Refs */
            decisive_evidence_refs: string[];
            /** Missing Evidence */
            missing_evidence: string[];
            /** Reason */
            reason: string;
            /** Rule Version */
            rule_version: string;
            /**
             * Evaluated At
             * Format: date-time
             */
            evaluated_at: string;
        };
        /**
         * UncollectedClaimType
         * @description Required facts that current extractors cannot yet supply; not Evidence.
         * @enum {string}
         */
        UncollectedClaimType: "DEPLOYED_CONSUMER_SCHEMA_VERSION" | "FUND_REQUEST_PROTOCOL_APPLICABILITY" | "REQUEST_ASSOCIATION" | "CALLBACK_EVENT_ASSOCIATION" | "FUND_REJECTION_WITHOUT_DISBURSEMENT";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_case_ui_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UICase"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_ui_cases__case_id__evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UIEvidenceList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_hypotheses_ui_cases__case_id__hypotheses_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UIHypothesisGraph"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_context_ui_cases__case_id__reasoning_context_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReasoningContextSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
