/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ui/cases/{case_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Summary */
        get: operations["get_summary_ui_cases__case_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/cases/{case_id}/frame": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Frame */
        get: operations["get_frame_ui_cases__case_id__frame_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/cases/{case_id}/evidence-page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evidence Page */
        get: operations["get_evidence_page_ui_cases__case_id__evidence_page_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/cases/{case_id}/evidence-items/{evidence_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Frame Evidence */
        get: operations["get_frame_evidence_ui_cases__case_id__evidence_items__evidence_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/cases/{case_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trace Page */
        get: operations["get_trace_page_ui_cases__case_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/cases/{case_id}/planner-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trace Page */
        get: operations["get_trace_page_ui_cases__case_id__planner_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/cases/{case_id}/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trace Page */
        get: operations["get_trace_page_ui_cases__case_id__tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/cases/{case_id}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trace Page */
        get: operations["get_trace_page_ui_cases__case_id__sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/cases/{case_id}/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trace Page */
        get: operations["get_trace_page_ui_cases__case_id__routes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/cases/{case_id}/knowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trace Page */
        get: operations["get_trace_page_ui_cases__case_id__knowledge_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/cases/{case_id}/work": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trace Page */
        get: operations["get_trace_page_ui_cases__case_id__work_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/cases/{case_id}/effects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trace Page */
        get: operations["get_trace_page_ui_cases__case_id__effects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/cases/{case_id}/recovery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trace Page */
        get: operations["get_trace_page_ui_cases__case_id__recovery_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/cases/{case_id}/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trace Page */
        get: operations["get_trace_page_ui_cases__case_id__evaluations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/cases/{case_id}/closure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trace Page */
        get: operations["get_trace_page_ui_cases__case_id__closure_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CaseBudget */
        CaseBudget: {
            /** Max Tool Calls */
            max_tool_calls: number;
            /**
             * Used Tool Calls
             * @default 0
             */
            used_tool_calls: number;
        };
        /**
         * CaseStatus
         * @enum {string}
         */
        CaseStatus: "NEW" | "INVESTIGATING" | "WAITING" | "ESCALATED" | "CLOSED" | "CLOSED_VERIFIED";
        /**
         * ClaimType
         * @enum {string}
         */
        ClaimType: "REQUEST_SENT" | "HTTP_RESPONSE_STATUS" | "FUND_BUSINESS_STATUS" | "LOAN_NO_PRESENT" | "LOAN_NOTE_REFERENCE" | "PAYMENT_FINALITY" | "PAYMENT_TRANSACTION_ID" | "PAYMENT_AMOUNT" | "PAYMENT_CURRENCY" | "PAYMENT_CUSTOMER_REF" | "PAYMENT_BENEFICIARY_REF" | "PAYMENT_ACCOUNT_REF" | "TRANSACTION_FUND_REQUEST_ID" | "CALLBACK_GATEWAY_RECEIVED" | "CALLBACK_SIGNATURE_VERIFIED" | "CALLBACK_PROTOCOL_VERSION" | "MESSAGE_CONSUME_STATUS" | "MESSAGE_DLQ" | "MESSAGE_ERROR_CODE" | "MESSAGE_ERROR_FIELD" | "MESSAGE_EXPECTED_FIELD_TYPE" | "MESSAGE_ACTUAL_FIELD_TYPE" | "CONSUMER_DEPLOYED_SCHEMA_VERSION" | "CONSUMER_ACCEPTED_PROTOCOL_VERSION" | "CONSUMER_LOAN_NO_FIELD_TYPE" | "ACCOUNTING_ENTRY_PRESENT" | "ASSET_STATUS" | "GUARANTEE_STATUS" | "GUARANTEE_VERSION" | "ASSET_DELIVERY_STATUS" | "ASSET_DELIVERY_EVENT_REF" | "PROTOCOL_FIELD_TYPE" | "PROTOCOL_BUSINESS_SEMANTICS" | "SOURCE_LOOKUP_STATUS";
        /**
         * Completeness
         * @enum {string}
         */
        Completeness: "COMPLETE" | "PARTIAL" | "UNKNOWN";
        /**
         * Currency
         * @enum {string}
         */
        Currency: "CNY" | "USD";
        /** EvidencePage */
        EvidencePage: {
            /** Items */
            items: components["schemas"]["UIEvidence"][];
            /** Total */
            total: number;
            /** Eligibility Denied Count */
            eligibility_denied_count: number;
            /** Frame Id */
            frame_id: string;
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * EvidenceStrength
         * @enum {string}
         */
        EvidenceStrength: "AUTHORITATIVE" | "STRONG" | "SUPPORTING" | "WEAK" | "HINT";
        /** FactCapsule */
        FactCapsule: {
            claim_type: components["schemas"]["ClaimType"];
            /** Value */
            value: boolean | number | string;
            subject: components["schemas"]["FactSubject"];
            /**
             * Business Time
             * Format: date-time
             */
            business_time: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            freshness: components["schemas"]["Freshness"];
            completeness: components["schemas"]["Completeness"];
            source: components["schemas"]["FactSource"];
            /** Protocol Version */
            protocol_version: string | null;
            /** Evidence Refs */
            evidence_refs: string[];
        };
        /** FactSource */
        FactSource: {
            tool: components["schemas"]["ToolName"];
            source_kind: components["schemas"]["SourceKind"];
            /** Source Version */
            source_version: string | null;
            /** Source As Of */
            source_as_of: string | null;
        };
        /** FactSubject */
        FactSubject: {
            kind: components["schemas"]["SubjectKind"];
            /** Identifier */
            identifier: string;
            /** Field */
            field: string | null;
            /** Internal Order Id */
            internal_order_id: string;
        };
        /** FinancialSubject */
        FinancialSubject: {
            /** Expected Principal Minor */
            expected_principal_minor: number;
            currency: components["schemas"]["Currency"];
            /** Customer Ref */
            customer_ref: string;
            /** Expected Beneficiary Ref */
            expected_beneficiary_ref: string;
            /** Expected Account Ref */
            expected_account_ref: string;
        };
        /** FinancialTruth */
        FinancialTruth: {
            claim_type: components["schemas"]["ClaimType"];
            /** Value */
            value: string | number | boolean;
            /** Evidence Refs */
            evidence_refs: string[];
            /**
             * Status
             * @enum {string}
             */
            status: "OBSERVED" | "UNKNOWN" | "CONFLICT";
        };
        /**
         * Freshness
         * @enum {string}
         */
        Freshness: "CURRENT" | "STALE" | "UNKNOWN";
        /** GapCapability */
        GapCapability: {
            /** Gap Id */
            gap_id: string;
            /** Available Tools */
            available_tools: components["schemas"]["ToolName"][];
            /** Unavailable Reason */
            unavailable_reason?: string | null;
        };
        /**
         * GapStatus
         * @enum {string}
         */
        GapStatus: "OPEN" | "SATISFIED" | "UNAVAILABLE";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HypothesisDefinition */
        HypothesisDefinition: {
            hypothesis_id: components["schemas"]["HypothesisId"];
            kind: components["schemas"]["HypothesisKind"];
            /** Statement */
            statement: string;
            /** Description */
            description: string;
            /** Confirmation Rule Id */
            confirmation_rule_id: string;
            /** Elimination Rule Id */
            elimination_rule_id: string;
            /** Relevant Claim Types */
            relevant_claim_types: components["schemas"]["ClaimType"][];
            parent_hypothesis_id?: components["schemas"]["HypothesisId"] | null;
        };
        /**
         * HypothesisId
         * @enum {string}
         */
        HypothesisId: "H1" | "H2" | "H3" | "H4" | "H5" | "H6" | "H6_SCHEMA_MISMATCH" | "H6_STALE_CONSUMER_SCHEMA" | "H7" | "H8";
        /**
         * HypothesisKind
         * @enum {string}
         */
        HypothesisKind: "CAUSAL" | "STATE" | "SEMANTIC_GUARD";
        /**
         * HypothesisStatus
         * @enum {string}
         */
        HypothesisStatus: "UNKNOWN" | "POSSIBLE" | "SUPPORTED" | "CONFIRMED" | "ELIMINATED";
        /**
         * IdentityDimension
         * @enum {string}
         */
        IdentityDimension: "FINALITY" | "TRANSACTION" | "REQUEST" | "AMOUNT" | "CURRENCY" | "CUSTOMER" | "BENEFICIARY" | "ACCOUNT";
        /**
         * IdentityMatch
         * @enum {string}
         */
        IdentityMatch: "MATCH" | "MISMATCH" | "UNKNOWN";
        /** InvestigationFrame */
        InvestigationFrame: {
            /** Frame Id */
            frame_id: string;
            /** Case Id */
            case_id: string;
            /**
             * Case Revision
             * Format: date-time
             */
            case_revision: string;
            /** Evidence Fingerprint */
            evidence_fingerprint: string;
            /** Registry Version */
            registry_version: string | null;
            /** Route Revision */
            route_revision: string | null;
            /** Latest Agent Run */
            latest_agent_run: string | null;
            /**
             * Assembled At
             * Format: date-time
             */
            assembled_at: string;
            /**
             * Route Summary
             * @default []
             */
            route_summary: components["schemas"]["TraceField"][];
            /** Investigation Allowed */
            investigation_allowed: boolean;
            /** Current Evidence Total */
            current_evidence_total: number;
            case_summary: components["schemas"]["UICase"];
            /** Financial Truth */
            financial_truth: components["schemas"]["FinancialTruth"][];
            financial_identity: components["schemas"]["PaymentIdentityContext"];
            /** Financial Identity Dimensions */
            financial_identity_dimensions: components["schemas"]["TraceField"][];
            /** Current Evidence */
            current_evidence: components["schemas"]["FactCapsule"][];
            hypotheses: components["schemas"]["UIHypothesisGraph"];
            /** Gap Capabilities */
            gap_capabilities: components["schemas"]["GapCapability"][];
            evidence: components["schemas"]["EvidencePage"];
            timeline: components["schemas"]["TracePage"];
            planner_trace: components["schemas"]["TracePage"];
            tool_trace: components["schemas"]["TracePage"];
            registry_source_trace: components["schemas"]["TracePage"];
            route_trace: components["schemas"]["TracePage"];
            knowledge_retrieval_trace: components["schemas"]["TracePage"];
            work_trace: components["schemas"]["TracePage"];
            side_effect_trace: components["schemas"]["TracePage"];
            recovery_trace: components["schemas"]["TracePage"];
            evaluation_trace: components["schemas"]["TracePage"];
            closure_trace: components["schemas"]["TracePage"];
            /**
             * Notice
             * @default READ ONLY · APPLIED ≠ VERIFIED · Historical guidance is not current Evidence
             */
            notice: string;
        };
        /** PaymentIdentityContext */
        PaymentIdentityContext: {
            result: components["schemas"]["IdentityMatch"];
            /** Mismatch Dimensions */
            mismatch_dimensions: components["schemas"]["IdentityDimension"][];
            /** Unknown Dimensions */
            unknown_dimensions: components["schemas"]["IdentityDimension"][];
            /** Candidate Transaction Count */
            candidate_transaction_count: number;
            /** Transaction Ref Preview */
            transaction_ref_preview: string[];
            /** Transaction Refs Digest */
            transaction_refs_digest: string;
            /** Evidence Ref Count */
            evidence_ref_count: number;
            /** Evidence Refs Digest */
            evidence_refs_digest: string;
            /** Evidence Refs */
            evidence_refs: string[];
            /** Verification Version */
            verification_version: string;
        };
        /**
         * PriorityClass
         * @enum {string}
         */
        PriorityClass: "SAFETY_CRITICAL" | "DISCRIMINATING" | "SUPPORTING";
        /**
         * SourceKind
         * @enum {string}
         */
        SourceKind: "PRIMARY" | "REPLICA" | "CACHE" | "INDEX";
        /**
         * SubjectKind
         * @enum {string}
         */
        SubjectKind: "ORDER" | "FUND_REQUEST" | "TRANSACTION" | "CALLBACK" | "MESSAGE" | "PROTOCOL";
        /**
         * ToolName
         * @enum {string}
         */
        ToolName: "get_asset_order" | "get_guarantee_order" | "get_fund_order" | "get_payment_transaction" | "get_loan_note" | "get_callback_gateway" | "get_callback_raw" | "get_messages" | "get_accounting" | "get_request_trace" | "get_asset_delivery" | "get_protocol";
        /** TraceField */
        TraceField: {
            /** Name */
            name: string;
            /** Value */
            value: string;
        };
        /** TraceItem */
        TraceItem: {
            /** Trace Id */
            trace_id: string;
            kind: components["schemas"]["TraceKind"];
            /** Occurred At */
            occurred_at?: string | null;
            /** Status */
            status: string;
            /**
             * Fields
             * @default []
             */
            fields: components["schemas"]["TraceField"][];
            /**
             * Evidence Refs
             * @default []
             */
            evidence_refs: string[];
            /**
             * Related Refs
             * @default []
             */
            related_refs: string[];
            /** Warning */
            warning?: string | null;
            /**
             * Historical
             * @default false
             */
            historical: boolean;
            /** @default CURRENT_OPERATIONAL */
            trace_trust_class: components["schemas"]["TraceTrustClass"];
        };
        /**
         * TraceKind
         * @enum {string}
         */
        TraceKind: "CaseCreated" | "ContextSnapshot" | "PlannerDecision" | "CALL_TOOL" | "Observation" | "EvidencePublished" | "ResumeWork" | "RemediationProposed" | "Approval" | "Effect" | "Recovery" | "Evaluation" | "Closed" | "RouteRevision" | "RegistrySource" | "KnowledgeRetrieval" | "WAIT" | "ESCALATE";
        /** TracePage */
        TracePage: {
            /** Frame Id */
            frame_id: string;
            /** Items */
            items: components["schemas"]["TraceItem"][];
            /** Total */
            total: number;
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * TraceTrustClass
         * @enum {string}
         */
        TraceTrustClass: "CURRENT_OPERATIONAL" | "ORGANIZATIONAL_GUIDANCE" | "VERIFIED_HISTORICAL_GUIDANCE" | "HISTORICAL_EVALUATION" | "CLOSURE_BOUND_CURRENT_EVALUATION";
        /** UIBasicCase */
        UIBasicCase: {
            /** Case Id */
            case_id: string;
            status: components["schemas"]["CaseStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** UICase */
        UICase: {
            /** Case Id */
            case_id: string;
            /** Internal Order Id */
            internal_order_id: string;
            status: components["schemas"]["CaseStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            budget: components["schemas"]["CaseBudget"];
            financial_subject: components["schemas"]["FinancialSubject"] | null;
        };
        /** UIEvidence */
        UIEvidence: {
            claim_type: components["schemas"]["ClaimType"];
            /** Value */
            value: boolean | number | string;
            subject: components["schemas"]["FactSubject"];
            /**
             * Business Time
             * Format: date-time
             */
            business_time: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            freshness: components["schemas"]["Freshness"];
            completeness: components["schemas"]["Completeness"];
            source: components["schemas"]["FactSource"];
            /** Protocol Version */
            protocol_version: string | null;
            /** Evidence Refs */
            evidence_refs: string[];
            /** Evidence Id */
            evidence_id: string;
            /** Observation Id */
            observation_id: string;
            /** Event Time */
            event_time: string | null;
            strength: components["schemas"]["EvidenceStrength"];
            /** Extractor Version */
            extractor_version: string;
        };
        /** UIGap */
        UIGap: {
            /** Gap Id */
            gap_id: string;
            /** Case Id */
            case_id: string;
            /** Hypothesis Ids */
            hypothesis_ids: components["schemas"]["HypothesisId"][];
            /** Question */
            question: string;
            /** Required Claim Types */
            required_claim_types: (components["schemas"]["ClaimType"] | components["schemas"]["UncollectedClaimType"])[];
            status: components["schemas"]["GapStatus"];
            /** Reason */
            reason: string;
            priority_class: components["schemas"]["PriorityClass"];
            /** Evidence Refs */
            evidence_refs: string[];
        };
        /** UIHypothesisGraph */
        UIHypothesisGraph: {
            /** Case Id */
            case_id: string;
            /** Rule Version */
            rule_version: string;
            /** Definitions */
            definitions: components["schemas"]["HypothesisDefinition"][];
            /** Hypotheses */
            hypotheses: components["schemas"]["UIHypothesisState"][];
            /** Open Gaps */
            open_gaps: components["schemas"]["UIGap"][];
        };
        /** UIHypothesisState */
        UIHypothesisState: {
            hypothesis_id: components["schemas"]["HypothesisId"];
            status: components["schemas"]["HypothesisStatus"];
            /** Supporting Evidence Refs */
            supporting_evidence_refs: string[];
            /** Contradicting Evidence Refs */
            contradicting_evidence_refs: string[];
            /** Decisive Evidence Refs */
            decisive_evidence_refs: string[];
            /** Missing Evidence */
            missing_evidence: string[];
            /** Reason */
            reason: string;
            /** Rule Version */
            rule_version: string;
            /**
             * Evaluated At
             * Format: date-time
             */
            evaluated_at: string;
        };
        /**
         * UncollectedClaimType
         * @description Required facts that current extractors cannot yet supply; not Evidence.
         * @enum {string}
         */
        UncollectedClaimType: "DEPLOYED_CONSUMER_SCHEMA_VERSION" | "FUND_REQUEST_PROTOCOL_APPLICABILITY" | "REQUEST_ASSOCIATION" | "CALLBACK_EVENT_ASSOCIATION" | "FUND_REJECTION_WITHOUT_DISBURSEMENT";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_summary_ui_cases__case_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UIBasicCase"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_frame_ui_cases__case_id__frame_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationFrame"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_page_ui_cases__case_id__evidence_page_get: {
        parameters: {
            query: {
                frame_id: string;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidencePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_frame_evidence_ui_cases__case_id__evidence_items__evidence_id__get: {
        parameters: {
            query: {
                frame_id: string;
            };
            header?: never;
            path: {
                case_id: string;
                evidence_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UIEvidence"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trace_page_ui_cases__case_id__timeline_get: {
        parameters: {
            query: {
                frame_id: string;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TracePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trace_page_ui_cases__case_id__planner_runs_get: {
        parameters: {
            query: {
                frame_id: string;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TracePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trace_page_ui_cases__case_id__tools_get: {
        parameters: {
            query: {
                frame_id: string;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TracePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trace_page_ui_cases__case_id__sources_get: {
        parameters: {
            query: {
                frame_id: string;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TracePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trace_page_ui_cases__case_id__routes_get: {
        parameters: {
            query: {
                frame_id: string;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TracePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trace_page_ui_cases__case_id__knowledge_get: {
        parameters: {
            query: {
                frame_id: string;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TracePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trace_page_ui_cases__case_id__work_get: {
        parameters: {
            query: {
                frame_id: string;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TracePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trace_page_ui_cases__case_id__effects_get: {
        parameters: {
            query: {
                frame_id: string;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TracePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trace_page_ui_cases__case_id__recovery_get: {
        parameters: {
            query: {
                frame_id: string;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TracePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trace_page_ui_cases__case_id__evaluations_get: {
        parameters: {
            query: {
                frame_id: string;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TracePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trace_page_ui_cases__case_id__closure_get: {
        parameters: {
            query: {
                frame_id: string;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TracePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
