"""Frozen pre-Step17 schema. Generated once, then reviewed."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from migrations.frozen_types import Vector
revision = '0016_baseline'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public")
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experience_vector_index',
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('document_id', sa.String(length=80), nullable=False),
    sa.Column('source_version', sa.String(length=64), nullable=False),
    sa.Column('embedding_space_id', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('source_status', sa.String(length=16), nullable=False),
    sa.Column('source_case_id', sa.String(length=128), nullable=True),
    sa.Column('business_domain', sa.String(length=64), nullable=True),
    sa.Column('environment', sa.String(length=64), nullable=True),
    sa.Column('funding_partner', sa.String(length=128), nullable=True),
    sa.Column('asset_partner', sa.String(length=128), nullable=True),
    sa.Column('guarantee_partner', sa.String(length=128), nullable=True),
    sa.Column('product_code', sa.String(length=128), nullable=True),
    sa.Column('protocol_versions', sa.String(length=1024), nullable=False),
    sa.Column('applicable_since', sa.String(length=40), nullable=False),
    sa.Column('applicable_until', sa.String(length=40), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('embedding', sa.JSON().with_variant(Vector(), "postgresql"), nullable=False),
    sa.Column('indexed_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'document_id', 'source_version', 'embedding_space_id')
    )
    op.create_index('ix_experience_vector_scope', 'experience_vector_index', ['tenant_id', 'source_status', 'embedding_space_id', 'business_domain', 'funding_partner', 'product_code'], unique=False)
    op.create_table('organizational_guidance_audit',
    sa.Column('sequence', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('object_id', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('from_status', sa.String(length=16), nullable=True),
    sa.Column('to_status', sa.String(length=16), nullable=False),
    sa.Column('recorded_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('sequence')
    )
    op.create_index(op.f('ix_organizational_guidance_audit_tenant_id'), 'organizational_guidance_audit', ['tenant_id'], unique=False)
    op.create_table('organizational_skills',
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('skill_id', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'skill_id', 'version')
    )
    op.create_table('registry_admin_audit',
    sa.Column('sequence', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('sequence')
    )
    op.create_index(op.f('ix_registry_admin_audit_tenant_id'), 'registry_admin_audit', ['tenant_id'], unique=False)
    op.create_table('registry_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('event', sa.String(length=20), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('occurred_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registry_case_snapshots',
    sa.Column('snapshot_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_table('registry_change_requests',
    sa.Column('change_request_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('inventory', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('change_request_id')
    )
    op.create_index(op.f('ix_registry_change_requests_tenant_id'), 'registry_change_requests', ['tenant_id'], unique=False)
    op.create_table('registry_heads',
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('registry_inventory_heads',
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('registry_inventory_previews',
    sa.Column('preview_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('confirmed_cr', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('preview_id')
    )
    op.create_index(op.f('ix_registry_inventory_previews_tenant_id'), 'registry_inventory_previews', ['tenant_id'], unique=False)
    op.create_table('registry_inventory_versions',
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('change_request_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'revision')
    )
    op.create_table('registry_versions',
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_index(op.f('ix_registry_versions_tenant_id'), 'registry_versions', ['tenant_id'], unique=False)
    op.create_table('retrieval_embedding_index_jobs',
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('document_type', sa.String(length=16), nullable=False),
    sa.Column('document_id', sa.String(length=80), nullable=False),
    sa.Column('source_version', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding_space_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('lease_token', sa.String(length=64), nullable=True),
    sa.Column('lease_until', sa.String(length=40), nullable=True),
    sa.Column('next_eligible_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('tenant_id', 'document_type', 'document_id', 'source_version', 'content_hash', 'embedding_space_id')
    )
    op.create_index('ix_embedding_job_ready', 'retrieval_embedding_index_jobs', ['status', 'next_eligible_at', 'lease_until'], unique=False)
    op.create_table('retrieval_embedding_spaces',
    sa.Column('space_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('space_id')
    )
    op.create_index('uq_retrieval_active_space', 'retrieval_embedding_spaces', ['status'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"), sqlite_where=sa.text("status = 'ACTIVE'"))
    op.create_table('retrieval_space_head',
    sa.Column('singleton', sa.Integer(), nullable=False),
    sa.Column('active_space', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('singleton')
    )
    op.create_table('simulations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=8), nullable=False),
    sa.Column('clock', sa.String(length=40), nullable=False),
    sa.Column('clock_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_vector_index',
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('document_id', sa.String(length=80), nullable=False),
    sa.Column('source_version', sa.String(length=64), nullable=False),
    sa.Column('embedding_space_id', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('source_status', sa.String(length=16), nullable=False),
    sa.Column('source_case_id', sa.String(length=128), nullable=True),
    sa.Column('business_domain', sa.String(length=64), nullable=True),
    sa.Column('environment', sa.String(length=64), nullable=True),
    sa.Column('funding_partner', sa.String(length=128), nullable=True),
    sa.Column('asset_partner', sa.String(length=128), nullable=True),
    sa.Column('guarantee_partner', sa.String(length=128), nullable=True),
    sa.Column('product_code', sa.String(length=128), nullable=True),
    sa.Column('protocol_versions', sa.String(length=1024), nullable=False),
    sa.Column('applicable_since', sa.String(length=40), nullable=False),
    sa.Column('applicable_until', sa.String(length=40), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('embedding', sa.JSON().with_variant(Vector(), "postgresql"), nullable=False),
    sa.Column('indexed_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'document_id', 'source_version', 'embedding_space_id')
    )
    op.create_index('ix_skill_vector_scope', 'skill_vector_index', ['tenant_id', 'source_status', 'embedding_space_id', 'business_domain', 'funding_partner', 'product_code'], unique=False)
    op.create_table('synthetic_external_effects',
    sa.Column('effect_key', sa.String(length=64), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('correlation_id', sa.String(length=80), nullable=False),
    sa.Column('external_ref', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('effect_key')
    )
    op.create_table('synthetic_remediation_tasks',
    sa.Column('task_id', sa.String(length=80), nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_synthetic_remediation_tasks_case_id'), 'synthetic_remediation_tasks', ['case_id'], unique=False)
    op.create_table('evaluation_ground_truth',
    sa.Column('simulation_id', sa.String(length=36), nullable=False),
    sa.Column('truth', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('simulation_id')
    )
    op.create_table('investigation_cases',
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('simulation_id', sa.String(length=36), nullable=False),
    sa.Column('grant_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('max_tool_calls', sa.Integer(), nullable=False),
    sa.Column('used_tool_calls', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_index(op.f('ix_investigation_cases_tenant_id'), 'investigation_cases', ['tenant_id'], unique=False)
    op.create_table('observation_faults',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('simulation_id', sa.String(length=36), nullable=False),
    sa.Column('policy', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registry_capabilities',
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('capability_id', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['version'], ['registry_versions.version'], ),
    sa.PrimaryKeyConstraint('version', 'capability_id')
    )
    op.create_table('registry_claim_authority_rules',
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('capability_id', sa.String(length=100), nullable=False),
    sa.Column('claim_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['version'], ['registry_versions.version'], ),
    sa.PrimaryKeyConstraint('version', 'capability_id', 'claim_type')
    )
    op.create_table('registry_systems',
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('system_id', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['version'], ['registry_versions.version'], ),
    sa.PrimaryKeyConstraint('version', 'system_id')
    )
    op.create_table('tool_grants',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('simulation_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=80), nullable=False),
    sa.Column('allowed_tools', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_table('tool_observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('simulation_id', sa.String(length=36), nullable=False),
    sa.Column('grant_hash', sa.String(length=64), nullable=False),
    sa.Column('tool', sa.String(length=50), nullable=False),
    sa.Column('request', sa.JSON(), nullable=False),
    sa.Column('observation', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('dispatch_correlation_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('world_snapshots',
    sa.Column('simulation_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('simulation_id', 'revision')
    )
    op.create_table('agent_checkpoints',
    sa.Column('run_id', sa.String(length=80), nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('last_completed_turn', sa.Integer(), nullable=False),
    sa.Column('last_snapshot_id', sa.String(length=64), nullable=False),
    sa.Column('last_decision_id', sa.String(length=64), nullable=True),
    sa.Column('last_call_id', sa.String(length=80), nullable=True),
    sa.Column('stop_status', sa.String(length=48), nullable=True),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['investigation_cases.case_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_agent_checkpoints_case_id'), 'agent_checkpoints', ['case_id'], unique=False)
    op.create_table('authorization_audit',
    sa.Column('sequence', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audit_id', sa.String(length=80), nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['investigation_cases.case_id'], ),
    sa.PrimaryKeyConstraint('sequence'),
    sa.UniqueConstraint('audit_id')
    )
    op.create_index(op.f('ix_authorization_audit_case_id'), 'authorization_audit', ['case_id'], unique=False)
    op.create_table('authorized_intents',
    sa.Column('intent_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['investigation_cases.case_id'], ),
    sa.PrimaryKeyConstraint('intent_id')
    )
    op.create_table('case_evidence',
    sa.Column('evidence_id', sa.String(length=66), nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('observation_id', sa.String(length=36), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['investigation_cases.case_id'], ),
    sa.ForeignKeyConstraint(['observation_id'], ['tool_observations.id'], ),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index(op.f('ix_case_evidence_case_id'), 'case_evidence', ['case_id'], unique=False)
    op.create_table('case_orchestration_audit',
    sa.Column('sequence', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['investigation_cases.case_id'], ),
    sa.PrimaryKeyConstraint('sequence')
    )
    op.create_index(op.f('ix_case_orchestration_audit_case_id'), 'case_orchestration_audit', ['case_id'], unique=False)
    op.create_table('case_orchestration_state',
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['investigation_cases.case_id'], ),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('case_resolution_signals',
    sa.Column('signal_id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['investigation_cases.case_id'], ),
    sa.PrimaryKeyConstraint('signal_id')
    )
    op.create_index(op.f('ix_case_resolution_signals_case_id'), 'case_resolution_signals', ['case_id'], unique=False)
    op.create_table('case_tool_calls',
    sa.Column('call_id', sa.String(length=36), nullable=False),
    sa.Column('dispatch_correlation_id', sa.String(length=36), nullable=True),
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('tool', sa.String(length=50), nullable=False),
    sa.Column('request', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('observation_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['investigation_cases.case_id'], ),
    sa.ForeignKeyConstraint(['observation_id'], ['tool_observations.id'], ),
    sa.PrimaryKeyConstraint('call_id'),
    sa.UniqueConstraint('case_id', 'sequence'),
    sa.UniqueConstraint('observation_id')
    )
    op.create_index(op.f('ix_case_tool_calls_case_id'), 'case_tool_calls', ['case_id'], unique=False)
    op.create_table('case_work_items',
    sa.Column('work_item_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('not_before', sa.Float(), nullable=False),
    sa.Column('lease_until', sa.Float(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['investigation_cases.case_id'], ),
    sa.PrimaryKeyConstraint('work_item_id')
    )
    op.create_index('ix_case_work_due', 'case_work_items', ['tenant_id', 'status', 'not_before'], unique=False)
    op.create_index(op.f('ix_case_work_items_case_id'), 'case_work_items', ['case_id'], unique=False)
    op.create_table('evaluation_handoff_outbox',
    sa.Column('sequence', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evaluation_run_id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['investigation_cases.case_id'], ),
    sa.PrimaryKeyConstraint('sequence'),
    sa.UniqueConstraint('evaluation_run_id')
    )
    op.create_index('ix_evaluation_handoff_pending', 'evaluation_handoff_outbox', ['tenant_id', 'status', 'sequence'], unique=False)
    op.create_table('evaluation_reports',
    sa.Column('evaluation_run_id', sa.String(length=80), nullable=False),
    sa.Column('report_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['investigation_cases.case_id'], ),
    sa.PrimaryKeyConstraint('evaluation_run_id')
    )
    op.create_index(op.f('ix_evaluation_reports_case_id'), 'evaluation_reports', ['case_id'], unique=False)
    op.create_index(op.f('ix_evaluation_reports_report_id'), 'evaluation_reports', ['report_id'], unique=False)
    op.create_table('investigation_safe_traces',
    sa.Column('trace_id', sa.String(length=80), nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['investigation_cases.case_id'], ),
    sa.PrimaryKeyConstraint('trace_id')
    )
    op.create_index(op.f('ix_investigation_safe_traces_case_id'), 'investigation_safe_traces', ['case_id'], unique=False)
    op.create_table('registry_case_route_revisions',
    sa.Column('route_revision_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('parent_revision_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['investigation_cases.case_id'], ),
    sa.ForeignKeyConstraint(['parent_revision_id'], ['registry_case_route_revisions.route_revision_id'], ),
    sa.PrimaryKeyConstraint('route_revision_id')
    )
    op.create_index(op.f('ix_registry_case_route_revisions_case_id'), 'registry_case_route_revisions', ['case_id'], unique=False)
    op.create_table('registry_case_routes',
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['investigation_cases.case_id'], ),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('verified_incident_experiences',
    sa.Column('experience_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('source_case_id', sa.String(length=80), nullable=False),
    sa.Column('closure_id', sa.String(length=64), nullable=False),
    sa.Column('report_id', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('signature_hash', sa.String(length=64), nullable=False),
    sa.Column('partner', sa.String(length=128), nullable=True),
    sa.Column('protocol', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['source_case_id'], ['investigation_cases.case_id'], ),
    sa.PrimaryKeyConstraint('experience_id'),
    sa.UniqueConstraint('tenant_id', 'closure_id', 'schema_version')
    )
    op.create_index('ix_experience_scope', 'verified_incident_experiences', ['tenant_id', 'partner', 'protocol', 'signature_hash'], unique=False)
    op.create_index(op.f('ix_verified_incident_experiences_tenant_id'), 'verified_incident_experiences', ['tenant_id'], unique=False)
    op.create_table('case_verified_closures',
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('closure_id', sa.String(length=64), nullable=False),
    sa.Column('evaluation_run_id', sa.String(length=80), nullable=False),
    sa.Column('report_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['investigation_cases.case_id'], ),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['evaluation_reports.evaluation_run_id'], ),
    sa.PrimaryKeyConstraint('case_id'),
    sa.UniqueConstraint('closure_id')
    )
    op.create_table('evidence_origins',
    sa.Column('evidence_id', sa.String(length=66), nullable=False),
    sa.Column('call_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['case_tool_calls.call_id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['case_evidence.evidence_id'], ),
    sa.PrimaryKeyConstraint('evidence_id', 'call_id')
    )
    op.create_table('execution_capabilities',
    sa.Column('capability_id', sa.String(length=80), nullable=False),
    sa.Column('intent_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('used_effect_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['intent_id'], ['authorized_intents.intent_id'], ),
    sa.PrimaryKeyConstraint('capability_id')
    )
    op.create_table('orchestration_agent_runs',
    sa.Column('run_id', sa.String(length=80), nullable=False),
    sa.Column('work_item_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['work_item_id'], ['case_work_items.work_item_id'], ),
    sa.PrimaryKeyConstraint('run_id'),
    sa.UniqueConstraint('work_item_id')
    )
    op.create_table('read_dispatch_recovery',
    sa.Column('call_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('dispatch_correlation_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('recovered_observation_id', sa.String(length=36), nullable=True),
    sa.Column('recovered_evidence_refs', sa.JSON(), nullable=False),
    sa.Column('attempted_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['case_tool_calls.call_id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['investigation_cases.case_id'], ),
    sa.PrimaryKeyConstraint('call_id')
    )
    op.create_index(op.f('ix_read_dispatch_recovery_case_id'), 'read_dispatch_recovery', ['case_id'], unique=False)
    op.create_table('registry_case_route_heads',
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('route_revision_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['investigation_cases.case_id'], ),
    sa.ForeignKeyConstraint(['route_revision_id'], ['registry_case_route_revisions.route_revision_id'], ),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('registry_dispatch_sources',
    sa.Column('call_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['case_tool_calls.call_id'], ),
    sa.PrimaryKeyConstraint('call_id')
    )
    op.create_table('remediation_approvals',
    sa.Column('approval_id', sa.String(length=80), nullable=False),
    sa.Column('intent_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['intent_id'], ['authorized_intents.intent_id'], ),
    sa.PrimaryKeyConstraint('approval_id')
    )
    op.create_table('capability_signatures',
    sa.Column('capability_id', sa.String(length=80), nullable=False),
    sa.Column('signature', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['execution_capabilities.capability_id'], ),
    sa.PrimaryKeyConstraint('capability_id')
    )
    op.create_table('side_effect_ledger',
    sa.Column('effect_id', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('capability_id', sa.String(length=80), nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['execution_capabilities.capability_id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['investigation_cases.case_id'], ),
    sa.PrimaryKeyConstraint('effect_id'),
    sa.UniqueConstraint('capability_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_side_effect_ledger_case_id'), 'side_effect_ledger', ['case_id'], unique=False)
    op.create_table('effect_recovery_attempts',
    sa.Column('recovery_id', sa.String(length=80), nullable=False),
    sa.Column('worker_id', sa.String(length=80), nullable=False),
    sa.Column('effect_id', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.Float(), nullable=False),
    sa.Column('completed_at', sa.Float(), nullable=True),
    sa.Column('source_status', sa.String(length=24), nullable=False),
    sa.Column('resolver_id', sa.String(length=80), nullable=False),
    sa.Column('result_status', sa.String(length=24), nullable=True),
    sa.Column('lookup_result', sa.JSON(), nullable=True),
    sa.Column('proof', sa.JSON(), nullable=True),
    sa.Column('proof_hash', sa.String(length=64), nullable=True),
    sa.Column('failure_code', sa.String(length=48), nullable=True),
    sa.ForeignKeyConstraint(['effect_id'], ['side_effect_ledger.effect_id'], ),
    sa.PrimaryKeyConstraint('recovery_id'),
    sa.UniqueConstraint('effect_id', 'sequence')
    )
    op.create_index(op.f('ix_effect_recovery_attempts_effect_id'), 'effect_recovery_attempts', ['effect_id'], unique=False)
    op.create_table('effect_recovery_audit',
    sa.Column('sequence', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('effect_id', sa.String(length=64), nullable=False),
    sa.Column('recovery_id', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['effect_id'], ['side_effect_ledger.effect_id'], ),
    sa.PrimaryKeyConstraint('sequence')
    )
    op.create_index(op.f('ix_effect_recovery_audit_effect_id'), 'effect_recovery_audit', ['effect_id'], unique=False)
    op.create_index(op.f('ix_effect_recovery_audit_recovery_id'), 'effect_recovery_audit', ['recovery_id'], unique=False)
    op.create_table('effect_recovery_state',
    sa.Column('effect_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('ledger_updated_at', sa.Float(), nullable=False),
    sa.Column('next_eligible_at', sa.Float(), nullable=False),
    sa.Column('lease_owner', sa.String(length=80), nullable=True),
    sa.Column('lease_until', sa.Float(), nullable=True),
    sa.Column('lease_token', sa.String(length=80), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('requires_escalation', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['effect_id'], ['side_effect_ledger.effect_id'], ),
    sa.PrimaryKeyConstraint('effect_id')
    )
    op.create_index(op.f('ix_effect_recovery_state_case_id'), 'effect_recovery_state', ['case_id'], unique=False)
    op.create_index('ix_recovery_due', 'effect_recovery_state', ['tenant_id', 'status', 'next_eligible_at'], unique=False)
    # ### end Alembic commands ###
    op.execute(sa.text("INSERT INTO retrieval_space_head (singleton, active_space) VALUES (1, NULL)"))

def downgrade():
    raise RuntimeError("Forward-only migration; use an audited restore or forward fix")
