"""Frozen additive deployment expansion. Generated once, then reviewed."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = '0017_expand'
down_revision = '0016_baseline'
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigation_frames',
    sa.Column('frame_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('case_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('frame_id')
    )
    op.create_index(op.f('ix_investigation_frames_case_id'), 'investigation_frames', ['case_id'], unique=False)
    op.create_index(op.f('ix_investigation_frames_expires_at'), 'investigation_frames', ['expires_at'], unique=False)
    op.create_index(op.f('ix_investigation_frames_tenant_id'), 'investigation_frames', ['tenant_id'], unique=False)
    op.create_table('retrieval_completeness',
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('document_type', sa.String(length=16), nullable=False),
    sa.Column('space_id', sa.String(length=64), nullable=False),
    sa.Column('indexed_generation', sa.Integer(), nullable=False),
    sa.Column('last_reconciled_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'document_type', 'space_id')
    )
    op.create_table('retrieval_source_generations',
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('document_type', sa.String(length=16), nullable=False),
    sa.Column('generation', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'document_type')
    )
    op.create_table('retrieval_space_admin_audit',
    sa.Column('audit_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('from_space', sa.String(length=64), nullable=False),
    sa.Column('to_space', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('schema_migration_audit',
    sa.Column('revision', sa.String(length=64), nullable=False),
    sa.Column('applied_at', sa.String(length=40), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('revision')
    )
    op.create_table('worker_heartbeats',
    sa.Column('worker_id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('worker_id')
    )
    op.create_index(op.f('ix_worker_heartbeats_tenant_id'), 'worker_heartbeats', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
    op.add_column("investigation_safe_traces", sa.Column("projection_version", sa.String(16), nullable=True, server_default="1"))
    op.create_index("ix_safe_trace_projection", "investigation_safe_traces", ["projection_version"])
    op.execute(sa.text("INSERT INTO schema_migration_audit VALUES ('0017_expand', CURRENT_TIMESTAMP, 'expand')"))
    op.execute(sa.text("INSERT INTO schema_migration_audit VALUES ('0016_baseline', CURRENT_TIMESTAMP, 'baseline verified')"))

def downgrade():
    raise RuntimeError("Forward-only migration; use an audited restore or forward fix")
