export type Permission = 'REGISTRY_VIEW' | 'REGISTRY_EDIT' | 'REGISTRY_SUBMIT' | 'REGISTRY_APPROVE' | 'REGISTRY_ACTIVATE' | 'REGISTRY_ROLLBACK' | 'REGISTRY_AUDIT';
export interface Scope { tenant_id: string; business_domain: string; environment: string; partner_role: string | null; partner_id: string | null; product_codes: string[]; protocol_versions: string[]; version_agnostic: boolean }
export interface SystemDefinition { system_id: string; company_system_code?: string | null; display_name: string; system_type: string; source_channel: string; owner_team: string; status: string; scope: Scope; effective_from: string; effective_until: string | null; draining_since: string | null; credential_ref: '[MASKED]' | null }
export interface Capability { capability_id: string; system_id: string; capability_type: string; tool_name: string; read_or_write: string; produces_claim_types: string[]; contributes_requirements: string[]; supports_lookup: boolean; authority_level: string; scope: Scope; adapter_id: string; query_contract_version: string; response_contract_version: string; status: string; effective_from: string; effective_until: string | null; draining_since: string | null; recovery: { supports_status_lookup: boolean; not_found_proves_no_effect: boolean; resolver_contract_version: string } }
export interface Authority { capability_id: string; claim_type: string; authority_level: string; subject_binding_required: boolean; identity_binding_required: boolean; freshness_requirement: string; completeness_requirement: string }
export interface Definition { tenant_id: string; systems: SystemDefinition[]; capabilities: Capability[]; authority_rules: Authority[] }
export interface ChangeRequest { change_request_id: string; tenant_id: string; base_registry_version: string | null; proposed_registry_version: string; revision: number; kind: string; status: string; title: string; reason: string; created_by: string; created_at: string; submitted_by: string | null; approved_by: string | null; activated_by: string | null; approval_comment?: string | null; rejection_reason?: string | null; base_inventory_revision?: number }
export interface DiffEntry { entity_id: string; fields: string[]; before_values?: Record<string, unknown>; after_values?: Record<string, unknown> }
export interface VersionDiff { systems_added: string[]; systems_removed: string[]; systems_changed: DiffEntry[]; capabilities_added: string[]; capabilities_removed: string[]; capabilities_changed: DiffEntry[]; authority_added: string[]; authority_removed: string[]; authority_changed: DiffEntry[]; routing_scope_changed: string[]; status_changed: string[]; risk_level: string; risk_reasons: string[] }
export interface Detail { change_request: ChangeRequest; definition: Definition; diff: VersionDiff; inventory_changes?: Inventory[] }
export interface Page<T> { items: T[]; total: number }
export interface Dashboard { active_version: string | null; inventory_revision: number; system_count: number; permissions: Permission[]; roles: string[]; identity: { user_id: string; display_name: string } }
export interface Catalog { system_types: string[]; source_channels: string[]; capability_types: string[]; partner_roles: string[]; authority_levels: string[]; tools: { tool_name: string; claims: string[]; requirements: string[] }[] }
export interface Impact { affected_active_case_count: number; affected_case_ids_digest: string; affected_partner_products: {asset_partner: string; funding_partner: string; product_code: string}[]; changed_capability_types: string[]; invalidated_snapshot_count: number; affected_pending_work_count: number; case_page: Page<string>; runtime_revalidation_scope: string; base_is_current: boolean }
export interface SourceMetadata { source_file_name: string; source_row_ref: string; source_file_hash: string; imported_by: string; imported_at: string }
export interface Membership { system_code: string; inventory_group: string; source_metadata: SourceMetadata }
export interface Inventory { system_code: string; system_name: string; system_type_label: string; description: string; main_functions: string; memberships: Membership[] }
export interface CompanySystemSummary { system_code: string; system_name: string; system_type_label: string; inventory_groups: string[]; agent_configuration_status: string; agent_source_count: number; capability_count: number }
export interface CompanySystemDetail { company_system: Inventory; inventory_groups: string[]; agent_configuration_status: string; agent_source_count: number; capability_count: number; registry_sources: SystemDefinition[]; capabilities: Capability[]; authority: Authority[] }
export interface Preview { preview_id: string; source_rows: number; unique_systems: number; shared_systems: string[]; groups: string[]; added: string[]; changed: string[]; unchanged: string[]; conflicts: {system_code: string; code: string; row_refs: string[]}[]; invalid: {row_ref: string; code: string}[]; rows: Inventory[] }
