// Presentation only: keep wire enums, identifiers and original evidence values intact.
const labels: Record<string, string> = {
  UNKNOWN: '未知', MATCH: '一致', MISMATCH: '不一致', CONFIRMED: '已确认',
  SUPPORTED: '有证据支持', POSSIBLE: '可能', ELIMINATED: '已排除',
  SAFETY_CRITICAL: '安全关键', DISCRIMINATING: '用于区分假设', SUPPORTING: '辅助支持',
  NEW: '新建', INVESTIGATING: '调查中', WAITING: '等待中', ESCALATED: '已升级',
  CLOSED: '已关闭', CLOSED_VERIFIED: '已验证结案', OPEN: '待补充', SATISFIED: '已满足',
  CURRENT: '当前有效', STALE: '已过时', COMPLETE: '完整', PARTIAL: '部分',
  SUCCESS: '成功', FAILED: '失败', PROCESSING: '处理中', TIMEOUT: '超时', NOT_FOUND: '未查到',
  SETTLED: '已结算', NOT_EXECUTED: '未执行', PENDING: '待处理', OBSERVED: '已观测',
  true: '是', false: '否', AUTHORITATIVE: '权威来源', STRONG: '强证据', WEAK: '弱证据', HINT: '线索',
  REQUEST: '资金请求', TRANSACTION: '支付交易', AMOUNT: '金额', CURRENCY: '币种',
  CUSTOMER: '客户', BENEFICIARY: '收款主体', ACCOUNT: '收款账户', FINALITY: '支付终态',
  Request: '请求链路', Fund: '资金方', Payment: '支付', Callback: '回调', Message: '消息',
  Guarantee: '担保方', Asset: '资产方', Protocol: '协议', Accounting: '记账',
  REQUEST_SENT: '请求已发送', HTTP_RESPONSE_STATUS: 'HTTP 响应状态',
  FUND_BUSINESS_STATUS: '资金方业务状态', LOAN_NO_PRESENT: '借据号是否存在',
  PAYMENT_FINALITY: '支付终态', PAYMENT_IDENTITY: '支付身份绑定',
  PAYMENT_TRANSACTION_ID: '支付交易编号', TRANSACTION_FUND_REQUEST_ID: '交易对应资金请求',
  PAYMENT_AMOUNT: '支付金额（分）', PAYMENT_CURRENCY: '支付币种',
  PAYMENT_CUSTOMER_REF: '支付客户引用', PAYMENT_BENEFICIARY_REF: '收款主体引用', PAYMENT_ACCOUNT_REF: '收款账户引用',
  CALLBACK_GATEWAY_RECEIVED: '网关已收到回调', CALLBACK_SIGNATURE_VERIFIED: '回调验签通过',
  CALLBACK_PROTOCOL_VERSION: '回调协议版本', MESSAGE_CONSUME_STATUS: '消息消费状态',
  MESSAGE_DLQ: '死信队列', MESSAGE_ERROR_CODE: '消息错误码', MESSAGE_ERROR_FIELD: '消息错误字段',
  MESSAGE_EXPECTED_FIELD_TYPE: '消费端期望字段类型', MESSAGE_ACTUAL_FIELD_TYPE: '实际字段类型',
  ACCOUNTING_ENTRY_PRESENT: '记账记录是否存在', ASSET_STATUS: '资产方状态',
  GUARANTEE_STATUS: '担保方状态', GUARANTEE_VERSION: '担保方订单版本',
  ASSET_DELIVERY_STATUS: '资产方通知状态', ASSET_DELIVERY_EVENT_REF: '资产方通知事件引用',
  PROTOCOL_FIELD_TYPE: '协议字段类型', PROTOCOL_BUSINESS_SEMANTICS: '协议业务语义',
  SOURCE_LOOKUP_STATUS: '来源查询结果', FUND_PROTOCOL_APPLICABILITY: '资金请求适用协议',
  FUND_REQUEST_PROTOCOL_APPLICABILITY: '资金请求协议关联', REQUEST_ASSOCIATION: '资金请求关联',
  CALLBACK_EVENT_ASSOCIATION: '回调事件关联', CALLBACK_CONSUMPTION: '回调消费',
  DEPLOYED_CONSUMER_SCHEMA_VERSION: '已部署消费端结构版本',
  CONSUMER_DEPLOYED_SCHEMA_VERSION: '消费端部署结构版本',
  CONSUMER_ACCEPTED_PROTOCOL_VERSION: '消费端支持协议版本', CONSUMER_LOAN_NO_FIELD_TYPE: '消费端借据号字段类型',
  CONSUMER_DEPLOYMENT_READINESS: '消费端部署就绪状态',
  NO_AVAILABLE_CAPABILITY_FOR_REQUIRED_FACT: '当前没有可获取所需事实的工具能力',
  get_trace: '查询请求链路', get_fund_loan_status: '查询资金方状态',
  get_request_trace: '查询请求链路', get_fund_order: '查询资金方订单',
  get_callback_gateway: '查询回调网关', get_callback_raw: '查询原始回调', get_loan_note: '查询借据',
  get_payment_transaction: '查询支付交易', get_callback: '查询回调网关',
  get_messages: '查询消息消费', get_protocol: '查询协议', get_guarantee_order: '查询担保方订单',
  get_asset_order: '查询资产方订单', get_accounting: '查询记账',
  get_consumer_deployment: '查询消费端部署', get_asset_delivery: '查询资产方通知',
  REQUEST_NOT_SENT: '请求未发送', FUND_NOT_ACCEPTED: '资金方未受理', FUND_PROCESSING_FAILED: '资金方处理失败',
  PAYMENT_SETTLED_WITHOUT_SUCCESSFUL_HTTP_RESPONSE: '支付已结算，但未收到成功的 HTTP 响应',
  CALLBACK_NOT_OBSERVED_AT_GATEWAY: '网关尚未观测到回调', CALLBACK_CONSUMPTION_FAILED: '回调消费失败',
  CALLBACK_SCHEMA_MISMATCH_TRIGGERED_FAILURE: '回调字段类型不匹配触发消费失败',
  STALE_CONSUMER_SCHEMA: '消费端使用过时的数据结构', ASSET_NOTIFICATION_FAILED: '资产方通知失败',
  FUND_SUCCESS_NOT_EQUAL_PAYMENT_FINALITY: '资金方业务成功不等于支付终态',
  CAUSAL: '原因假设', STATE: '状态假设', SEMANTIC_GUARD: '语义边界',
  CaseCreated: '任务创建', ContextSnapshot: '上下文快照', PlannerDecision: '规划决策',
  CALL_TOOL: '调用工具', Observation: '观测记录', EvidencePublished: '证据发布',
  ResumeWork: '恢复任务', RemediationProposed: '修复建议', Approval: '审批', Effect: '副作用',
  Recovery: '恢复记录', Evaluation: '独立评估', Closed: '结案', RouteRevision: '路由修订',
  RegistrySource: '系统来源', KnowledgeRetrieval: '知识检索', WAIT: '等待', ESCALATE: '升级处理',
  CREATED: '已创建', PUBLISHED: '已发布', DISPATCHED: '已派发', ERROR: '异常', ROUTED: '已路由',
  TRUSTED_INITIAL: '可信初始配置', VERIFIED: '已验证', VALID: '有效', REJECTED: '已拒绝', RECORDED: '已记录',
  ORGANIZATIONAL_GUIDANCE: '组织经验指导', VERIFIED_HISTORICAL_GUIDANCE: '已验证的历史指导',
  READY: '就绪', CLAIMED: '已领取', BLOCKED: '已阻断', COMPLETED: '已完成', CANCELED: '已取消',
  PREPARED: '已准备', ACCEPTED: '已受理', APPLIED: '已应用', FAILED_CONFIRMED: '已确认失败',
  PASS: '通过', FAIL: '未通过', INCONCLUSIVE: '尚无定论', NOT_APPLICABLE: '不适用', IN_PROGRESS: '进行中',
  PROPOSED: '已提议', APPROVED: '已批准', PROTOCOL_VERIFIED: '协议已验证',
  VECTOR_UNAVAILABLE: '向量检索不可用', POST_EFFECT_MESSAGE_STATUS: '执行后的消息状态',
  'HISTORICAL GUIDANCE; NOT CURRENT CASE EVIDENCE': '历史指导资料，不属于当前任务证据',
  'Organizational guidance; not current Evidence': '组织指导资料，不属于当前证据',
  'Dispatch timestamp was not recorded': '未记录派发时间', 'APPLIED ≠ VERIFIED': '已应用 ≠ 已验证',
  'Historical evaluation; current state requires re-verification': '历史评估结果；当前状态需要重新验证',
  'IndependentEvaluator PASS + VerifiedClosure CAS': '独立评估通过，并完成结案版本校验',
  'Intent ≠ Authorization': '修复意图 ≠ 执行授权',
  TRUSTED_CONTROL: '可信控制信息', UNTRUSTED_EXTERNAL_DATA: '不可信外部数据',
  DETERMINISTIC_DERIVED: '确定性派生信息', READ_ONLY: '只读', LOW: '低', MEDIUM: '中', HIGH: '高',
  NO_NEW_FINANCIAL_INTENT: '禁止创建新的资金意图', UNKNOWN_IS_NOT_FAILED: '未知不等于失败',
  TOOL_SUCCESS_IS_NOT_BUSINESS_OUTCOME: '工具调用成功不等于业务成功',
  ACTIVE: '已激活', DISABLED: '已停用', DRAINING: '退出中', DRAFT: '草稿', SUBMITTED: '待审批',
  NOT_CONFIGURED: '未配置', PARTIALLY_CONFIGURED: '部分配置', CONFIGURED: '已配置',
  READ: '读取', WRITE: '写入', SIMULATOR: '模拟环境', TEST: '测试环境', PROD: '生产环境',
  ASSET: '资产方', FUNDING: '资金方', GUARANTEE: '担保方', DIAGNOSTIC: '诊断来源',
  INTERNAL_SYSTEM: '内部系统', PARTNER_API: '合作方接口', HIGH_RISK: '高风险',
  PARTNER_OFFICIAL_API: '合作方官方接口', PRIMARY: '主数据源', REPLICA: '副本', CACHE: '缓存', INDEX: '索引', OK: '查询完成',
  ASSET_CONVERGENCE: '资产方状态收敛', CALLBACK_DELIVERY: '回调送达',
  DEPLOYED_CONSUMER_SCHEMA: '已部署消费端结构', ACCOUNTING_CONVERGENCE: '记账状态收敛',
  ACTIVATED: '已激活', CONFIGURATION: '能力配置', INVENTORY: '公司资料', ROLLBACK: '回滚',
  REGISTRY_VIEWER: '查看者', REGISTRY_EDITOR: '编辑者', REGISTRY_APPROVER: '审批者', REGISTRY_ADMIN: '管理员',
  subject_binding_required: '要求绑定业务主体', identity_binding_required: '要求绑定身份',
};

const fields: Record<string, string> = {
  tool: '工具', sequence: '调用序号', observation_status: '观测状态', observed_at: '观测时间',
  claim_type: '事实类型', claim_types: '事实类型', company_system_code: '公司系统简称', display_name: '系统名称',
  source_channel: '来源通道', system_id: '系统编号', capability_id: '能力编号', registry_version: '系统清单版本',
  tool_name: '工具名称', authority: '来源权威性', route_revision: '路由版本', parent_revision: '上一版本',
  protocol_version: '协议版本', change_reason: '变更原因', snapshot_id: '快照编号', candidate_id: '候选编号',
  candidate_count: '候选数量', action_type: '动作类型', target_gaps: '目标缺口', expected_claims: '预期事实',
  reason_summary: '简要依据', rejections: '拒绝原因', selected: '已选动作', model: '模型', provider: '模型服务商',
  rank_priority: '缺口优先级', rank_novel_requirement_coverage: '新增需求覆盖', rank_coverage: '缺口覆盖',
  rank_hypothesis_discrimination: '假设区分能力', rank_economy: '成本与延迟', rank_repeated_query_penalty: '重复查询扣分',
  build_status: '构建状态', degradation: '降级状态', skills: '调查技能', experiences: '历史经验',
  embedding_space: '向量空间', hard_filter_candidate_count: '硬过滤候选数', vector_candidate_count: '向量候选数',
  reranked_count: '重排数量', selected_skill_ids: '已选技能编号', selected_experience_ids: '已选经验编号',
  vector_latency_ms: '向量检索耗时（毫秒）', rerank_latency_ms: '重排耗时（毫秒）', latency_ms: '耗时（毫秒）',
  skill_id: '技能编号', version: '版本', strategies: '调查策略', invariants: '安全约束', applicable_scope: '适用范围',
  experience_alias: '经验别名', outcome: '结果', similarity_features: '相似特征', tool_sequence: '工具顺序', lessons: '经验总结',
  work_type: '任务类型', reason_code: '原因码', trigger: '触发来源', not_before: '最早执行时间', attempt_count: '尝试次数',
  verification_requirements: '验证要求', approval_state: '审批状态', next_eligible_at: '下次允许处理时间',
  requires_escalation: '是否需要升级', source_status: '原状态', result_status: '结果状态', failure_code: '失败码',
  dimension: '验证维度', report_ref: '报告引用', overall_verdict: '整体结论', reason_codes: '原因码',
  required_claims_missing: '缺失的必要事实', requirements: '验证要求', outcome_path: '结果路径',
  partner_id: '合作方编号', partner_role: '合作方角色', asset_partner_id: '资产方编号', fund_partner_id: '资金方编号',
  product_code: '产品编码', environment: '环境', business_domain: '业务域', tenant_id: '租户编号',
  task: '任务契约', safety_constraints: '安全约束', budget: '调查预算', available_tools: '可用工具',
  financial_identity: '资金身份核验', hypotheses: '故障假设', open_evidence_gaps: '待补充证据',
  current_facts: '当前事实', history_digest: '历史摘要',
};

export const displayLabel = (value: string): string => labels[value] ?? value;
export const fieldLabel = (value: string): string => fields[value] ?? labels[value] ?? value;
